sudo: false

language: node_js

node_js:
  - '4'

before_script:
  - wget 'https://releases.hashicorp.com/consul/0.6.2/consul_0.6.2_linux_amd64.zip'
  - unzip "consul_0.6.2_linux_amd64.zip"
  - ./consul --version
  
script: 
  - ./consul agent -server -bootstrap -data-dir /tmp/consul &
  - sleep 15 && npm run test && killall consul
